print("------DICE SIMULATOR------")
print("A small beginner level project on Dice Simulator")
import random
x ="YES"
while x=="YES":
    number=random.randint(1,6)
    if(number==1):
        print("---------")
        print("|       |")
        print("|   O   |")
        print("|       |")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 1")
    if(number==2):
        print("---------")
        print("|O      |")
        print("|       |")
        print("|      O|")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 2")
    if(number==3):
        print("---------")
        print("|O      |")
        print("|   O   |")
        print("|      O|")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 3")
    if(number==4):
        print("---------")
        print("|O     O|")
        print("|       |")
        print("|O     O|")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 4")
    if(number==5):
        print("---------")
        print("|O     O|")
        print("|   O   |")
        print("|O     O|")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 5")
    if(number==6):
        print("---------")
        print("|O     O|")
        print("|O     O|")
        print("|O     O|")
        print("---------")
        print(" ")
        print("The dice is rolled and the output is 6")
    x=input("Type YES to roll the dice again")